spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: root

    jpa:
        generate-ddl: true
        show-sql: true
        
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQL8Dialect
